---

- name: update & upgrade
  apt:
     update_cache: true
     upgrade: true

- name: install packages
  package: name={{ packages }} state=latest
     
- name: install python packages
  pip: name={{ python_packages }} state=latest

